id: P000647
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13012
  title: གསང་སྔགས་ལམ་འགྲེལ་དང་ཞལ་གདམས་དམར་ཁྲིད་བཅས།
  author: ''
  volumes:
    626a1d9fda774d3cb0f2ac633d25585e:
      image_group_id: I1KG13085
      title: ''
      volume_number: 1
      total_pages: 232
