id: P000647
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:56:08.355752
source_metadata:
  id: bdr:W1KG13012
  title: གསང་སྔགས་ལམ་འགྲེལ་དང་ཞལ་གདམས་དམར་ཁྲིད་བཅས།
  author: ''
  volumes:
    626a1d9fda774d3cb0f2ac633d25585e:
      image_group_id: I1KG13085
      title: ''
      volume_number: 1
      total_pages: 232
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
